registry: ${env("REGISTRY","")}
owner: ${env("OWNER", env("GITHUB_REPOSITORY_OWNER",""))}
platforms:
  - linux/amd64
push: false
check: auto
hash:
  tag_length: 8
targets:
  src:
    dockerfile: Dockerfile
    context: docker/src
    deps: []
    hash_mode: self
    image: engine-src
    latest: true
  # service with sqlite config
  conductor:
    dockerfile: Dockerfile
    context: docker/conductor
    deps:
      - src
    hash_mode: self
    image: engine-conductor
    latest: true
  # build the UI isloated
  ui:
    dockerfile: Dockerfile
    context: docker/ui
    deps:
      - src
    hash_mode: self+deps
    image: engine-ui
    latest: true
  # target image with sqlite config and ui included
  sqlite-and-ui:
    dockerfile: Dockerfile
    context: docker/sqlite-and-ui
    deps:
      - conductor
      - ui
    hash_mode: self
    image: engine-sqlite-and-ui
    latest: true
